services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - mean-network

  backend:
    image: shiva425/mean-backend:latest
    container_name: backend
    restart: always
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      MONGODB_URI: mongodb://admin:password@mongodb:27017/mean_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - mean-network

  frontend:
    image: shiva425/mean-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - mean-network

volumes:
  mongodb_data:

networks:
  mean-network:
    driver: bridge
